### ISSUE TITLE
Crashes when monitoring server is in different timezone than urbackup server

### ISSUE THREAD

**Issue by yennor** [edvler/check_mk-urbackup-check#5]
I've reinstalled my monitoring server and accidentally put it into UTC instead of CET timezone. At the moment UTC is two hours behind CET.
When a new backup is done, it always ends in a crash of the urbackup monitoring plugin since to the plugin it seems that the backups are made in the future ([Timezones are evil ;-)](https://xkcd.com/1883/)).

ValueError (Cannot render negative timespan)

File "/omd/sites/rmm/lib/python3/cmk/base/agent_based/checking/_checking.py", line 413, in get_aggregated_result
    consume_check_results(
  File "/omd/sites/rmm/lib/python3/cmk/base/api/agent_based/checking_classes.py", line 494, in consume_check_results
    for subr in subresults:
  File "/omd/sites/rmm/lib/python3/cmk/base/api/agent_based/register/check_plugins.py", line 93, in filtered_generator
    for element in generator(*args, **kwargs):
  File "/omd/sites/rmm/local/lib/python3/cmk/base/plugins/agent_based/urbackup_check.py", line 85, in check_urbackup
    infotext = 'last ' + backup_type + ': ' + render.datetime(time.mktime(stamp)) + ' (Age: ' + render.timespan(old) + ' warn/crit at ' + render.timespan(warn) + '/' + render.timespan(crit) + ')'
  File "/omd/sites/rmm/lib/python3/cmk/base/api/agent_based/render.py", line 107, in timespan
    ts = " ".join(_gen_timespan_chunks(float(seconds), nchunks=2))
  File "/omd/sites/rmm/lib/python3/cmk/base/api/agent_based/render.py", line 73, in _gen_timespan_chunks
    raise ValueError("Cannot render negative timespan")

{'nchunks': 2, 'seconds': -6058.270578622818}

**Comment by edvler** [comment]
Thats realy a hard one.
I didn't found a real solution for this problem. Timezone calculations are realy evil :)

Do you have an idea?

**Comment by edvler** [comment]
I've created a timezone arware version.
If the client and the check-mk server are in differenz timezones, the check-mk servers timezone is used for rendering the time.

e.g.
**Client (timezone offset +0200) sends:**
XXXXXX;;;;;-;;;;;False;;;;;2023-07-14_23:05+0200;;;;;True

**The check-mk server (timezone UTC) converts it to**
last imagebackup: Jul 14 2023 21:05:00 (Age: 9 hours 35 minutes warn/crit at 9 days 0 hours/10 days 0 hours)


Please download the mkp version 1.2.4 from the dist folder.

It also necessary to place the new urbackup_check script in the /usr/lib/check_mk_agent/plugins folder, because the script now provides the timezone offset.


Please give me feedback if it works! :)

**Comment by yennor** [comment]
sorry I didn't reply you before. I've got family visiting for some weeks and I'm trying, quite unsuccessfully, to somehow merge family and work life.
and yes. either using UTC for everything or otherwise using "timezoned" variables is the way to go.
I'll test it next week.

**Comment by yennor** [comment]
i've tested it for a few days, and so far I didn't get any error messages. So it seems to be working. THanks a lot :-).
